window.initdata = function initdata() {

  if (!localStorage.getItem('users')) {
    const users = [
      // Admins 
      {
        name: "Ken",
        email: "ken@123",
        password: "123",
        userType: "admin"
      },
      {
        name: "Catarina",
        email: "cat@123",
        password: "123",
        userType: "admin"
      },
      {
        name: "esmadAdmin",
        email: "esmadAd@email.com",
        password: "123",
        userType: "admin"
      },

      // Students
      {
        name: "EsmadAl",
        surname: "Aluno",
        email: "esmadAl@email.com",
        location: "Vila do Conde",
        password: "esmadal",
        userType: "aluno",
        favourites:[],
        rewardUsed:[],
        classesTaken:[]
      },
      {
        name: "Tiago",
        surname: "Costa",
        email: "tiago.costa@email.com",
        location: "Lisboa",
        password: "tg456",
        userType: "aluno",
        favourites:[],
        rewardUsed:[],
        classestTaken:[]
      },
      {
        name: "Beatriz",
        surname: "Silva",
        email: "beatriz.silva@email.com",
        location: "Porto",
        userType: "aluno",
        favourites:[],
        rewardUsed:[],
        classesTaken:[]
      },

      // TUTORS 
      {
        name: "Ana",
        surname: "Moura",
        email: "ana@tutor.pt",
        location: "Lisboa",
        password: "tutor123",
        subjects: ["ES-Matemática A", "ES-Física e Química A"], 
        levels: ["secundario"],
        modality: ["Presencial"], 
        phone: "912345678",
        bio: "Professora com 10 anos de experiência no ensino secundário.",
        educationLevel: "Ensino Secundário",
        price: 20,
        image: "/assets/svg/tutor1.svg",
        specialNeeds: "Sim", 
        favoriteCount: 5,
        createdAt: "2024-04-01T10:00:00",
        userType: "tutor",
        isAuthorized:true
      },
      {
        name: "Carlos",
        surname: "Lopes",
        email: "carlos@tutor.pt",
        location: "Coimbra",
        password: "abcd123",
        subjects: ["ES-História", "ES-Geografia A"],
        levels: ["secundario"],
        modality: ["Online"],
        phone: "913456789",
        bio: "Apaixonado por história, com experiência em ensino remoto.",
        educationLevel: "Ensino Secundário",
        price: 18,
        image: "/assets/svg/tutor2.svg",
        specialNeeds: "Não",
        favoriteCount: 8,
        createdAt: "2024-04-05T14:30:00",
        userType: "tutor",
        isAuthorized:true
      },
      {
        name: "Ana",
        surname: "Ferreira",
        email: "ana.ferreira@tutor.pt",
        location: "Lisboa",
        password: "ana456",
        subjects: ["ES-Matemática A", "ES-Física e Química A"],
        levels: ["secundario"],
        modality: ["Online"],
        phone: "914567890",
        bio: "Explicadora dedicada, com foco em preparação para exames nacionais.",
        educationLevel: "Ensino Secundário",
        price: 22,
        specialNeeds: "Sim",
        favoriteCount: 12,
        image: "/assets/svg/tutor3.svg",
        createdAt: "2024-04-06T14:30:00",
        userType: "tutor",
        isAuthorized:true
      },
      {
        name: "Mariana",
        surname: "Pereira",
        email: "mariana.pereira@tutor.pt",
        location: "Braga",
        password: "mari789",
        subjects: ["EB-Inglês", "EB-Português", "ES-Português"],
        levels: ["ambos"], 
        modality: ["Online"],
        phone: "912345678",
        bio: "Sou licenciada em Línguas e Literaturas Modernas e dou explicações há mais de 5 anos.",
        educationLevel: ["Ensino Básico","Ensino Secundário"],
        price: 15,
        specialNeeds: "Não",
        image: "/assets/svg/tutor4.svg",
        favoriteCount: 3,
        createdAt: "2024-04-03T14:30:00",
        userType: "tutor",
        isAuthorized:false,
      },
      {
        name: "EsmadTT",
        surname: "Tutor",
        email: "esmad@tutor.pt",
        location: "Vila do Conde",
        password: "esmadtt",
        subjects: ["EB-Português"],
        levels: ["basico"], 
        modality: ["Presencial"],
        phone: "915678901",
        bio: "Experiência com alunos do 3.º ciclo e reforço de gramática.",
        educationLevel: "Ensino Básico",
        price: 15,
        specialNeeds: "Não",
        favoriteCount: 15,
        image: "/assets/svg/tutor6.svg",
        createdAt: "2024-05-10T14:30:00",
        userType: "tutor",
        isAuthorized:true
      },
      {
      name: "João",
      surname: "Silva",
      email: "joao.silva@tutor.pt",
      location: "Porto",
      password: "joaopass",
      subjects: ["ES-Matemática A", "ES-Física e Química A"],
      levels: ["secundario"],
      modality: ["Presencial", "Online"],
      phone: "917123456",
      bio: "Engenheiro apaixonado por ensino, com 7 anos de experiência.",
      educationLevel: "Ensino Secundário",
      price: 25,
      specialNeeds: "Não",
      favoriteCount: 10,
      image: "/assets/svg/tutor7.svg",
      createdAt: "2024-03-15T10:00:00",
      userType: "tutor",
      isAuthorized: true
    },
    {
      name: "Sofia",
      surname: "Martins",
      email: "sofia.martins@tutor.pt",
      location: "Lisboa",
      password: "sofiapass",
      subjects: ["EB-Português", "EB-História"],
      levels: ["basico"],
      modality: ["Online"],
      phone: "918234567",
      bio: "Professora de português para crianças e jovens.",
      educationLevel: "Ensino Básico",
      price: 12,
      specialNeeds: "Sim",
      favoriteCount: 7,
      image: "/assets/svg/tutor13.svg",
      createdAt: "2024-01-22T12:00:00",
      userType: "tutor",
      isAuthorized: true
    },
    {
      name: "Miguel",
      surname: "Costa",
      email: "miguel.costa@tutor.pt",
      location: "Coimbra",
      password: "miguelpass",
      subjects: ["ES-Geografia A", "ES-História"],
      levels: ["secundario"],
      modality: ["Presencial"],
      phone: "919345678",
      bio: "Historiador com experiência em aulas particulares presenciais.",
      educationLevel: "Ensino Secundário",
      price: 20,
      specialNeeds: "Não",
      favoriteCount: 4,
      image: "/assets/svg/tutor8.svg",
      createdAt: "2024-02-10T09:30:00",
      userType: "tutor",
      isAuthorized: true
    },
    {
      name: "Carla",
      surname: "Almeida",
      email: "carla.almeida@tutor.pt",
      location: "Braga",
      password: "carlapass",
      subjects: ["EB-Matemática", "EB-Ciências Naturais"],
      levels: ["basico"],
      modality: ["Online", "Presencial"],
      phone: "916456789",
      bio: "Professora focada em explicar matemática e ciências para o básico.",
      educationLevel: "Ensino Básico",
      price: 15,
      specialNeeds: "Sim",
      favoriteCount: 9,
      image: "/assets/svg/tutor12.svg",
      createdAt: "2024-03-20T11:00:00",
      userType: "tutor",
      isAuthorized: true
    },
    {
      name: "Ricardo",
      surname: "Fernandes",
      email: "ricardo.fernandes@tutor.pt",
      location: "Lisboa",
      password: "ricardopass",
      subjects: ["ES-Física e Química A", "ES-Matemática A"],
      levels: ["secundario"],
      modality: ["Presencial"],
      phone: "917567890",
      bio: "Físico dedicado ao ensino, com boas referências dos alunos.",
      educationLevel: "Ensino Secundário",
      price: 28,
      specialNeeds: "Não",
      favoriteCount: 13,
      image: "/assets/svg/tutor9.svg",
      createdAt: "2024-04-15T13:00:00",
      userType: "tutor",
      isAuthorized: true
    },
    {
      name: "Helena",
      surname: "Ribeiro",
      email: "helena.ribeiro@tutor.pt",
      location: "Porto",
      password: "helenapass",
      subjects: ["ES-Inglês", "EB-Inglês"],
      levels: ["ambos"],
      modality: ["Online"],
      phone: "918678901",
      bio: "Professora de inglês com certificado CELTA e experiência online.",
      educationLevel: "Ensino Básico e Secundário",
      price: 18,
      specialNeeds: "Sim",
      favoriteCount: 11,
      image: "/assets/svg/tutor11.svg",
      createdAt: "2024-03-05T10:30:00",
      userType: "tutor",
      isAuthorized: true
    },
    {
      name: "Tiago",
      surname: "Silva",
      email: "tiago.silva@tutor.pt",
      location: "Vila do Conde",
      password: "tiagopass",
      subjects: ["EB-Português", "EB-História"],
      levels: ["basico"],
      modality: ["Presencial"],
      phone: "919789012",
      bio: "Professor com experiência a ajudar alunos do 3º ciclo.",
      educationLevel: "Ensino Básico",
      price: 14,
      specialNeeds: "Não",
      favoriteCount: 6,
      image: "/assets/svg/tutor10.svg",
      createdAt: "2024-02-28T14:00:00",
      userType: "tutor",
      isAuthorized: true
    },
    {
      name: "Patrícia",
      surname: "Moreira",
      email: "patricia.moreira@tutor.pt",
      location: "Lisboa",
      password: "patriciapass",
      subjects: ["ES-Filosofia", "ES-Português"],
      levels: ["secundario"],
      modality: ["Online"],
      phone: "916890123",
      bio: "Especialista em filosofia e literatura para ensino secundário.",
      educationLevel: "Ensino Secundário",
      price: 20,
      specialNeeds: "Sim",
      favoriteCount: 7,
      image: "/assets/svg/tutor15.svg",
      createdAt: "2024-04-10T15:30:00",
      userType: "tutor",
      isAuthorized: true
    },
    {
      name: "Bruno",
      surname: "Mendes",
      email: "bruno.mendes@tutor.pt",
      location: "Coimbra",
      password: "brunopass",
      subjects: ["ES-Matemática A", "EB-Matemática"],
      levels: ["ambos"],
      modality: ["Presencial"],
      phone: "917901234",
      bio: "Explicador paciente e detalhista em matemática.",
      educationLevel: "Ensino Básico e Secundário",
      price: 23,
      specialNeeds: "Não",
      favoriteCount: 10,
      image: "/assets/svg/tutor16.svg",
      createdAt: "2024-03-18T09:00:00",
      userType: "tutor",
      isAuthorized: true
    },
    {
      name: "Lúcia",
      surname: "Gomes",
      email: "lucia.gomes@tutor.pt",
      location: "Braga",
      password: "luciagass",
      subjects: ["EB-Português", "ES-Português"],
      levels: ["ambos"],
      modality: ["Online", "Presencial"],
      phone: "916012345",
      bio: "Professora dedicada ao ensino da língua portuguesa.",
      educationLevel: "Ensino Básico e Secundário",
      price: 17,
      specialNeeds: "Sim",
      favoriteCount: 8,
      image: "/assets/svg/tutor17.svg",
      createdAt: "2024-03-12T11:45:00",
      userType: "tutor",
      isAuthorized: true
    },
    {
      name: "Rui",
      surname: "Sousa",
      email: "rui.sousa@tutor.pt",
      location: "Lisboa",
      password: "ruipass",
      subjects: ["ES-Física e Química A", "ES-Biologia A"],
      levels: ["secundario"],
      modality: ["Presencial"],
      phone: "917234567",
      bio: "Biólogo e professor com experiência no ensino secundário.",
      educationLevel: "Ensino Secundário",
      price: 26,
      specialNeeds: "Não",
      favoriteCount: 9,
      image: "/assets/svg/tutor18.svg",
      createdAt: "2024-04-01T14:20:00",
      userType: "tutor",
      isAuthorized: true
    },
    {
      name: "Isabel",
      surname: "Pinto",
      email: "isabel.pinto@tutor.pt",
      location: "Porto",
      password: "isabelpass",
      subjects: ["ES-Inglês", "EB-Inglês"],
      levels: ["ambos"],
      modality: ["Online"],
      phone: "918345678",
      bio: "Professora com experiência em preparação para exames internacionais.",
      educationLevel: "Ensino Básico e Secundário",
      price: 19,
      specialNeeds: "Sim",
      favoriteCount: 5,
      image: "/assets/svg/tutor19.svg",
      createdAt: "2024-02-25T10:10:00",
      userType: "tutor",
      isAuthorized: true
    },
    {
      name: "Filipe",
      surname: "Carvalho",
      email: "filipe.carvalho@tutor.pt",
      location: "Vila do Conde",
      password: "filipepass",
      subjects: ["EB-Matemática", "EB-Ciências Naturais"],
      levels: ["basico"],
      modality: ["Presencial"],
      phone: "919456789",
      bio: "Professor entusiasta com foco no 3º ciclo do básico.",
      educationLevel: "Ensino Básico",
      price: 16,
      specialNeeds: "Não",
      favoriteCount: 7,
      image: "/assets/svg/tutor20.svg",
      createdAt: "2024-03-30T12:00:00",
      userType: "tutor",
      isAuthorized: true
    },
    {
      name: "Marta",
      surname: "Silva",
      email: "marta.silva@tutor.pt",
      location: "Lisboa",
      password: "martapass",
      subjects: ["ES-Português", "ES-Filosofia"],
      levels: ["secundario"],
      modality: ["Online", "Presencial"],
      phone: "916567890",
      bio: "Explicadora apaixonada por literatura e filosofia.",
      educationLevel: "Ensino Secundário",
      price: 21,
      specialNeeds: "Sim",
      favoriteCount: 6,
      image: "/assets/svg/tutor21.svg",
      createdAt: "2024-04-12T13:30:00",
      userType: "tutor",
      isAuthorized: true
    },
    // {
    //   name: "Paulo",
    //   surname: "Teixeira",
    //   email: "paulo.teixeira@tutor.pt",
    //   location: "Coimbra",
    //   password: "paulopass",
    //   subjects: ["ES-Física e Química A", "ES-Matemática A"],
    //   levels: ["secundario"],
    //   modality: ["Online"],
    //   phone: "917678901",
    //   bio: "Professor com experiência em explicações online para o ensino secundário.",
    //   educationLevel: "Ensino Secundário",
    //   price: 24,
    //   specialNeeds: "Não",
    //   favoriteCount: 11,
    //   image: "/assets/svg/tutor10.svg",
    //   createdAt: "2024-03-28T15:00:00",
    //   userType: "tutor",
    //   isAuthorized: true
    // },
    // {
    //   name: "Diana",
    //   surname: "Sousa",
    //   email: "diana.sousa@tutor.pt",
    //   location: "Braga",
    //   password: "dianapass",
    //   subjects: ["EB-Inglês", "EB-Português"],
    //   levels: ["basico"],
    //   modality: ["Presencial", "Online"],
    //   phone: "918789012",
    //   bio: "Professora dinâmica com paixão por línguas.",
    //   educationLevel: "Ensino Básico",
    //   price: 14,
    //   specialNeeds: "Sim",
    //   favoriteCount: 8,
    //   image: "/assets/svg/tutor22.svg",
    //   createdAt: "2024-04-02T10:20:00",
    //   userType: "tutor",
    //   isAuthorized: true
    // },
    // {
    //   name: "Fábio",
    //   surname: "Melo",
    //   email: "fabio.melo@tutor.pt",
    //   location: "Porto",
    //   password: "fabiopass",
    //   subjects: ["ES-Geografia A", "ES-História"],
    //   levels: ["secundario"],
    //   modality: ["Online"],
    //   phone: "919890123",
    //   bio: "Especialista em geografia com método prático de ensino.",
    //   educationLevel: "Ensino Secundário",
    //   price: 19,
    //   specialNeeds: "Não",
    //   favoriteCount: 7,
    //   image: "/assets/svg/tutor23.svg",
    //   createdAt: "2024-04-08T11:30:00",
    //   userType: "tutor",
    //   isAuthorized: true
    // }

    ];

    localStorage.setItem('users', JSON.stringify(users));
  }

  // Education levels 
  if (!localStorage.educationLevels) {
    const educationLevels = [
      {
        id: 1,
        name: "Ensino Básico (3.º Ciclo)",
        subjects: [
          "EB-Português",
          "EB-Inglês",
          "EB-Francês",
          "EB-Espanhol",
          "EB-História",
          "EB-Geografia",
          "EB-Matemática",
          "EB-Ciências Naturais",
          "EB-Físico-Química"
        ]
      },
      {
        id: 2,
        name: "Ensino Secundário",
        subjects: [
          "ES-Português",
          "ES-Língua Estrangeira",
          "ES-Filosofia",
          "ES-Matemática A",
          "ES-Geometria Descritiva A",
          "ES-Física e Química A",
          "ES-Biologia e Geologia",
          "ES-Economia A",
          "ES-Geografia A",
          "ES-História B",
          "ES-Literatura Portuguesa"
        ]
      }
    ];

    localStorage.setItem('educationLevels', JSON.stringify(educationLevels));
  }

  // Subjects 
  if (!localStorage.getItem('subjects')) {
const subjects = [
  "Português", "Inglês", "Francês", "Espanhol",
  "História", "Geografia", "Matemática",
  "Ciências Naturais", "Físico-Química",
  "Língua Estrangeira", "Filosofia", "Matemática A",
  "Geometria Descritiva A", "Física e Química A",
  "Biologia e Geologia", "Economia A", "Geografia A",
  "História B", "Literatura Portuguesa"
];

    localStorage.setItem('subjects', JSON.stringify(subjects));
  }

  // Locations
  if (!localStorage.locations) {
    const locations = [
      "Porto", "Lisboa", "Braga", "Coimbra", "Vila do Conde", "Faro"
    ];
    localStorage.setItem('locations', JSON.stringify(locations));
  }
};
initdata();